language: php
php:
  - 7.1
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
install:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - curl -SOL https://phpoole.org/phpoole.phar
  - php phpoole.phar -v
before_script:
  - composer run-script fake
script:
  - php build.php -e=prod
after_success:
  - bash deploy.sh
